name: Setup the repository and dependencies
description: Check out the repo, install pinned Python and Poetry version, make deps

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: snok/install-poetry@v1
      with:
        version: "2.1.3"
        virtualenvs-create: true
        virtualenvs-in-project: true

# vim: set nowrap tw=100:
