name: PyPI

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags')}}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install Dependencies
        run: make install
      - name: Build Wheel
        run: make build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
