name: Test

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: test-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

env:
  COLUMNS: 100
  PYTHONWARNINGS: error

jobs:
  test:
    name: ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target:
          - black
          - dapperdata
          - mypy
          - pytest
          - ruff
          - tomlsort

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install Dependencies
        run: make install
      - name: Test
        run: make test/${{matrix.target}}

# vim: set nowrap tw=100:
