name: Test

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: test-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

env:
  COLUMNS: 100

jobs:
  test:
    name: ${{matrix.python-version}}/${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        target:
          - mypy
          - pytest
        include:
          - target: pytest-cov
            python-version: "3.14"

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v5
      - name: "Set up dependencies and install"
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{matrix.python-version}}
      - name: Test
        run: make test/${{matrix.target}}

# vim: set nowrap tw=100:
